### ISSUE TITLE
1) P1: Implementar un proyecto en Proteus, mediante el cual puedan simular una conexión con Arduino

### ISSUE THREAD

**Issue by Leytonale** [ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea7-grupo-5#1]
La consigna es encender y apagar un led en la simulación usando protocolo de comunicaciones Bluetooth. La comunicación es entre el Smartphone o entorno virtual (PC) y el Proteus.

**Comment by lilenguzman01** [comment]
Terminado
